/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppManagersIndexRouteImport } from './routes/_app/managers/index'
import { Route as AppManagersNewRouteImport } from './routes/_app/managers/new'
import { Route as AppMembersAccessRouteImport } from './routes/_app/members/access'
import { Route as AppMembersCounselRouteImport } from './routes/_app/members/counsel'
import { Route as AppMembersDormantRouteImport } from './routes/_app/members/dormant'
import { Route as AppMembersNewRouteImport } from './routes/_app/members/new'
import { Route as AppPerformancesIndexRouteImport } from './routes/_app/performances/index'
import { Route as AppPerformancesContentsRouteImport } from './routes/_app/performances/contents'
import { Route as AppCommunityBoardsIndexRouteImport } from './routes/_app/community/boards/index'
import { Route as AppCommunityBoardsNewRouteImport } from './routes/_app/community/boards/new'
import { Route as AppManagersManagerIdIndexRouteImport } from './routes/_app/managers/$managerId/index'
import { Route as AppManagersManagerIdEditRouteImport } from './routes/_app/managers/$managerId/edit'
import { Route as AppMembersMemberIdIndexRouteImport } from './routes/_app/members/$memberId/index'
import { Route as AppMembersMemberIdEditRouteImport } from './routes/_app/members/$memberId/edit'
import { Route as AppMembersActiveAllRouteImport } from './routes/_app/members/active/all'
import { Route as AppMembersActiveFlaggedRouteImport } from './routes/_app/members/active/flagged'
import { Route as AppMembersActiveGeneralRouteImport } from './routes/_app/members/active/general'
import { Route as AppMembersAppealsIndexRouteImport } from './routes/_app/members/appeals/index'
import { Route as AppMembersAppealsAppealIdRouteImport } from './routes/_app/members/appeals/$appealId'
import { Route as AppMembersWithdrawnIndexRouteImport } from './routes/_app/members/withdrawn/index'
import { Route as AppMembersWithdrawnMemberIdRouteImport } from './routes/_app/members/withdrawn/$memberId'
import { Route as AppPerformancesPerformanceIdIndexRouteImport } from './routes/_app/performances/$performanceId/index'
import { Route as AppPerformancesPerformanceIdEditRouteImport } from './routes/_app/performances/$performanceId/edit'
import { Route as AppTicketingPrintersIndexRouteImport } from './routes/_app/ticketing/printers/index'
import { Route as AppTicketingPrintersNewRouteImport } from './routes/_app/ticketing/printers/new'
import { Route as AppCommunityBoardsBoardIdIndexRouteImport } from './routes/_app/community/boards/$boardId/index'
import { Route as AppCommunityBoardsBoardIdEditRouteImport } from './routes/_app/community/boards/$boardId/edit'
import { Route as AppTicketingPrintersPrinterIdIndexRouteImport } from './routes/_app/ticketing/printers/$printerId/index'
import { Route as AppTicketingPrintersPrinterIdEditRouteImport } from './routes/_app/ticketing/printers/$printerId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagersIndexRoute = AppManagersIndexRouteImport.update({
  id: '/managers/',
  path: '/managers/',
  getParentRoute: () => AppRoute,
} as any)
const AppManagersNewRoute = AppManagersNewRouteImport.update({
  id: '/managers/new',
  path: '/managers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersAccessRoute = AppMembersAccessRouteImport.update({
  id: '/members/access',
  path: '/members/access',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersCounselRoute = AppMembersCounselRouteImport.update({
  id: '/members/counsel',
  path: '/members/counsel',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersDormantRoute = AppMembersDormantRouteImport.update({
  id: '/members/dormant',
  path: '/members/dormant',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersNewRoute = AppMembersNewRouteImport.update({
  id: '/members/new',
  path: '/members/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformancesIndexRoute = AppPerformancesIndexRouteImport.update({
  id: '/performances/',
  path: '/performances/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformancesContentsRoute = AppPerformancesContentsRouteImport.update({
  id: '/performances/contents',
  path: '/performances/contents',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityBoardsIndexRoute = AppCommunityBoardsIndexRouteImport.update({
  id: '/community/boards/',
  path: '/community/boards/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityBoardsNewRoute = AppCommunityBoardsNewRouteImport.update({
  id: '/community/boards/new',
  path: '/community/boards/new',
  getParentRoute: () => AppRoute,
} as any)
const AppManagersManagerIdIndexRoute =
  AppManagersManagerIdIndexRouteImport.update({
    id: '/managers/$managerId/',
    path: '/managers/$managerId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppManagersManagerIdEditRoute =
  AppManagersManagerIdEditRouteImport.update({
    id: '/managers/$managerId/edit',
    path: '/managers/$managerId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppMembersMemberIdIndexRoute = AppMembersMemberIdIndexRouteImport.update({
  id: '/members/$memberId/',
  path: '/members/$memberId/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersMemberIdEditRoute = AppMembersMemberIdEditRouteImport.update({
  id: '/members/$memberId/edit',
  path: '/members/$memberId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersActiveAllRoute = AppMembersActiveAllRouteImport.update({
  id: '/members/active/all',
  path: '/members/active/all',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersActiveFlaggedRoute = AppMembersActiveFlaggedRouteImport.update({
  id: '/members/active/flagged',
  path: '/members/active/flagged',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersActiveGeneralRoute = AppMembersActiveGeneralRouteImport.update({
  id: '/members/active/general',
  path: '/members/active/general',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersAppealsIndexRoute = AppMembersAppealsIndexRouteImport.update({
  id: '/members/appeals/',
  path: '/members/appeals/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersAppealsAppealIdRoute =
  AppMembersAppealsAppealIdRouteImport.update({
    id: '/members/appeals/$appealId',
    path: '/members/appeals/$appealId',
    getParentRoute: () => AppRoute,
  } as any)
const AppMembersWithdrawnIndexRoute =
  AppMembersWithdrawnIndexRouteImport.update({
    id: '/members/withdrawn/',
    path: '/members/withdrawn/',
    getParentRoute: () => AppRoute,
  } as any)
const AppMembersWithdrawnMemberIdRoute =
  AppMembersWithdrawnMemberIdRouteImport.update({
    id: '/members/withdrawn/$memberId',
    path: '/members/withdrawn/$memberId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPerformancesPerformanceIdIndexRoute =
  AppPerformancesPerformanceIdIndexRouteImport.update({
    id: '/performances/$performanceId/',
    path: '/performances/$performanceId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppPerformancesPerformanceIdEditRoute =
  AppPerformancesPerformanceIdEditRouteImport.update({
    id: '/performances/$performanceId/edit',
    path: '/performances/$performanceId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppTicketingPrintersIndexRoute =
  AppTicketingPrintersIndexRouteImport.update({
    id: '/ticketing/printers/',
    path: '/ticketing/printers/',
    getParentRoute: () => AppRoute,
  } as any)
const AppTicketingPrintersNewRoute = AppTicketingPrintersNewRouteImport.update({
  id: '/ticketing/printers/new',
  path: '/ticketing/printers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityBoardsBoardIdIndexRoute =
  AppCommunityBoardsBoardIdIndexRouteImport.update({
    id: '/community/boards/$boardId/',
    path: '/community/boards/$boardId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCommunityBoardsBoardIdEditRoute =
  AppCommunityBoardsBoardIdEditRouteImport.update({
    id: '/community/boards/$boardId/edit',
    path: '/community/boards/$boardId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppTicketingPrintersPrinterIdIndexRoute =
  AppTicketingPrintersPrinterIdIndexRouteImport.update({
    id: '/ticketing/printers/$printerId/',
    path: '/ticketing/printers/$printerId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppTicketingPrintersPrinterIdEditRoute =
  AppTicketingPrintersPrinterIdEditRouteImport.update({
    id: '/ticketing/printers/$printerId/edit',
    path: '/ticketing/printers/$printerId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/managers/new': typeof AppManagersNewRoute
  '/members/access': typeof AppMembersAccessRoute
  '/members/counsel': typeof AppMembersCounselRoute
  '/members/dormant': typeof AppMembersDormantRoute
  '/members/new': typeof AppMembersNewRoute
  '/performances/contents': typeof AppPerformancesContentsRoute
  '/managers/': typeof AppManagersIndexRoute
  '/performances/': typeof AppPerformancesIndexRoute
  '/community/boards/new': typeof AppCommunityBoardsNewRoute
  '/managers/$managerId/edit': typeof AppManagersManagerIdEditRoute
  '/members/$memberId/edit': typeof AppMembersMemberIdEditRoute
  '/members/active/all': typeof AppMembersActiveAllRoute
  '/members/active/flagged': typeof AppMembersActiveFlaggedRoute
  '/members/active/general': typeof AppMembersActiveGeneralRoute
  '/members/appeals/$appealId': typeof AppMembersAppealsAppealIdRoute
  '/members/withdrawn/$memberId': typeof AppMembersWithdrawnMemberIdRoute
  '/performances/$performanceId/edit': typeof AppPerformancesPerformanceIdEditRoute
  '/ticketing/printers/new': typeof AppTicketingPrintersNewRoute
  '/community/boards/': typeof AppCommunityBoardsIndexRoute
  '/managers/$managerId/': typeof AppManagersManagerIdIndexRoute
  '/members/$memberId/': typeof AppMembersMemberIdIndexRoute
  '/members/appeals/': typeof AppMembersAppealsIndexRoute
  '/members/withdrawn/': typeof AppMembersWithdrawnIndexRoute
  '/performances/$performanceId/': typeof AppPerformancesPerformanceIdIndexRoute
  '/ticketing/printers/': typeof AppTicketingPrintersIndexRoute
  '/community/boards/$boardId/edit': typeof AppCommunityBoardsBoardIdEditRoute
  '/ticketing/printers/$printerId/edit': typeof AppTicketingPrintersPrinterIdEditRoute
  '/community/boards/$boardId/': typeof AppCommunityBoardsBoardIdIndexRoute
  '/ticketing/printers/$printerId/': typeof AppTicketingPrintersPrinterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/managers/new': typeof AppManagersNewRoute
  '/members/access': typeof AppMembersAccessRoute
  '/members/counsel': typeof AppMembersCounselRoute
  '/members/dormant': typeof AppMembersDormantRoute
  '/members/new': typeof AppMembersNewRoute
  '/performances/contents': typeof AppPerformancesContentsRoute
  '/managers': typeof AppManagersIndexRoute
  '/performances': typeof AppPerformancesIndexRoute
  '/community/boards/new': typeof AppCommunityBoardsNewRoute
  '/managers/$managerId/edit': typeof AppManagersManagerIdEditRoute
  '/members/$memberId/edit': typeof AppMembersMemberIdEditRoute
  '/members/active/all': typeof AppMembersActiveAllRoute
  '/members/active/flagged': typeof AppMembersActiveFlaggedRoute
  '/members/active/general': typeof AppMembersActiveGeneralRoute
  '/members/appeals/$appealId': typeof AppMembersAppealsAppealIdRoute
  '/members/withdrawn/$memberId': typeof AppMembersWithdrawnMemberIdRoute
  '/performances/$performanceId/edit': typeof AppPerformancesPerformanceIdEditRoute
  '/ticketing/printers/new': typeof AppTicketingPrintersNewRoute
  '/community/boards': typeof AppCommunityBoardsIndexRoute
  '/managers/$managerId': typeof AppManagersManagerIdIndexRoute
  '/members/$memberId': typeof AppMembersMemberIdIndexRoute
  '/members/appeals': typeof AppMembersAppealsIndexRoute
  '/members/withdrawn': typeof AppMembersWithdrawnIndexRoute
  '/performances/$performanceId': typeof AppPerformancesPerformanceIdIndexRoute
  '/ticketing/printers': typeof AppTicketingPrintersIndexRoute
  '/community/boards/$boardId/edit': typeof AppCommunityBoardsBoardIdEditRoute
  '/ticketing/printers/$printerId/edit': typeof AppTicketingPrintersPrinterIdEditRoute
  '/community/boards/$boardId': typeof AppCommunityBoardsBoardIdIndexRoute
  '/ticketing/printers/$printerId': typeof AppTicketingPrintersPrinterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/managers/new': typeof AppManagersNewRoute
  '/_app/members/access': typeof AppMembersAccessRoute
  '/_app/members/counsel': typeof AppMembersCounselRoute
  '/_app/members/dormant': typeof AppMembersDormantRoute
  '/_app/members/new': typeof AppMembersNewRoute
  '/_app/performances/contents': typeof AppPerformancesContentsRoute
  '/_app/managers/': typeof AppManagersIndexRoute
  '/_app/performances/': typeof AppPerformancesIndexRoute
  '/_app/community/boards/new': typeof AppCommunityBoardsNewRoute
  '/_app/managers/$managerId/edit': typeof AppManagersManagerIdEditRoute
  '/_app/members/$memberId/edit': typeof AppMembersMemberIdEditRoute
  '/_app/members/active/all': typeof AppMembersActiveAllRoute
  '/_app/members/active/flagged': typeof AppMembersActiveFlaggedRoute
  '/_app/members/active/general': typeof AppMembersActiveGeneralRoute
  '/_app/members/appeals/$appealId': typeof AppMembersAppealsAppealIdRoute
  '/_app/members/withdrawn/$memberId': typeof AppMembersWithdrawnMemberIdRoute
  '/_app/performances/$performanceId/edit': typeof AppPerformancesPerformanceIdEditRoute
  '/_app/ticketing/printers/new': typeof AppTicketingPrintersNewRoute
  '/_app/community/boards/': typeof AppCommunityBoardsIndexRoute
  '/_app/managers/$managerId/': typeof AppManagersManagerIdIndexRoute
  '/_app/members/$memberId/': typeof AppMembersMemberIdIndexRoute
  '/_app/members/appeals/': typeof AppMembersAppealsIndexRoute
  '/_app/members/withdrawn/': typeof AppMembersWithdrawnIndexRoute
  '/_app/performances/$performanceId/': typeof AppPerformancesPerformanceIdIndexRoute
  '/_app/ticketing/printers/': typeof AppTicketingPrintersIndexRoute
  '/_app/community/boards/$boardId/edit': typeof AppCommunityBoardsBoardIdEditRoute
  '/_app/ticketing/printers/$printerId/edit': typeof AppTicketingPrintersPrinterIdEditRoute
  '/_app/community/boards/$boardId/': typeof AppCommunityBoardsBoardIdIndexRoute
  '/_app/ticketing/printers/$printerId/': typeof AppTicketingPrintersPrinterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/managers/new'
    | '/members/access'
    | '/members/counsel'
    | '/members/dormant'
    | '/members/new'
    | '/performances/contents'
    | '/managers/'
    | '/performances/'
    | '/community/boards/new'
    | '/managers/$managerId/edit'
    | '/members/$memberId/edit'
    | '/members/active/all'
    | '/members/active/flagged'
    | '/members/active/general'
    | '/members/appeals/$appealId'
    | '/members/withdrawn/$memberId'
    | '/performances/$performanceId/edit'
    | '/ticketing/printers/new'
    | '/community/boards/'
    | '/managers/$managerId/'
    | '/members/$memberId/'
    | '/members/appeals/'
    | '/members/withdrawn/'
    | '/performances/$performanceId/'
    | '/ticketing/printers/'
    | '/community/boards/$boardId/edit'
    | '/ticketing/printers/$printerId/edit'
    | '/community/boards/$boardId/'
    | '/ticketing/printers/$printerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/managers/new'
    | '/members/access'
    | '/members/counsel'
    | '/members/dormant'
    | '/members/new'
    | '/performances/contents'
    | '/managers'
    | '/performances'
    | '/community/boards/new'
    | '/managers/$managerId/edit'
    | '/members/$memberId/edit'
    | '/members/active/all'
    | '/members/active/flagged'
    | '/members/active/general'
    | '/members/appeals/$appealId'
    | '/members/withdrawn/$memberId'
    | '/performances/$performanceId/edit'
    | '/ticketing/printers/new'
    | '/community/boards'
    | '/managers/$managerId'
    | '/members/$memberId'
    | '/members/appeals'
    | '/members/withdrawn'
    | '/performances/$performanceId'
    | '/ticketing/printers'
    | '/community/boards/$boardId/edit'
    | '/ticketing/printers/$printerId/edit'
    | '/community/boards/$boardId'
    | '/ticketing/printers/$printerId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/managers/new'
    | '/_app/members/access'
    | '/_app/members/counsel'
    | '/_app/members/dormant'
    | '/_app/members/new'
    | '/_app/performances/contents'
    | '/_app/managers/'
    | '/_app/performances/'
    | '/_app/community/boards/new'
    | '/_app/managers/$managerId/edit'
    | '/_app/members/$memberId/edit'
    | '/_app/members/active/all'
    | '/_app/members/active/flagged'
    | '/_app/members/active/general'
    | '/_app/members/appeals/$appealId'
    | '/_app/members/withdrawn/$memberId'
    | '/_app/performances/$performanceId/edit'
    | '/_app/ticketing/printers/new'
    | '/_app/community/boards/'
    | '/_app/managers/$managerId/'
    | '/_app/members/$memberId/'
    | '/_app/members/appeals/'
    | '/_app/members/withdrawn/'
    | '/_app/performances/$performanceId/'
    | '/_app/ticketing/printers/'
    | '/_app/community/boards/$boardId/edit'
    | '/_app/ticketing/printers/$printerId/edit'
    | '/_app/community/boards/$boardId/'
    | '/_app/ticketing/printers/$printerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/managers/': {
      id: '/_app/managers/'
      path: '/managers'
      fullPath: '/managers/'
      preLoaderRoute: typeof AppManagersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/managers/new': {
      id: '/_app/managers/new'
      path: '/managers/new'
      fullPath: '/managers/new'
      preLoaderRoute: typeof AppManagersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/access': {
      id: '/_app/members/access'
      path: '/members/access'
      fullPath: '/members/access'
      preLoaderRoute: typeof AppMembersAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/counsel': {
      id: '/_app/members/counsel'
      path: '/members/counsel'
      fullPath: '/members/counsel'
      preLoaderRoute: typeof AppMembersCounselRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/dormant': {
      id: '/_app/members/dormant'
      path: '/members/dormant'
      fullPath: '/members/dormant'
      preLoaderRoute: typeof AppMembersDormantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/new': {
      id: '/_app/members/new'
      path: '/members/new'
      fullPath: '/members/new'
      preLoaderRoute: typeof AppMembersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performances/': {
      id: '/_app/performances/'
      path: '/performances'
      fullPath: '/performances/'
      preLoaderRoute: typeof AppPerformancesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performances/contents': {
      id: '/_app/performances/contents'
      path: '/performances/contents'
      fullPath: '/performances/contents'
      preLoaderRoute: typeof AppPerformancesContentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community/boards/': {
      id: '/_app/community/boards/'
      path: '/community/boards'
      fullPath: '/community/boards/'
      preLoaderRoute: typeof AppCommunityBoardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community/boards/new': {
      id: '/_app/community/boards/new'
      path: '/community/boards/new'
      fullPath: '/community/boards/new'
      preLoaderRoute: typeof AppCommunityBoardsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/managers/$managerId/': {
      id: '/_app/managers/$managerId/'
      path: '/managers/$managerId'
      fullPath: '/managers/$managerId/'
      preLoaderRoute: typeof AppManagersManagerIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/managers/$managerId/edit': {
      id: '/_app/managers/$managerId/edit'
      path: '/managers/$managerId/edit'
      fullPath: '/managers/$managerId/edit'
      preLoaderRoute: typeof AppManagersManagerIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/$memberId/': {
      id: '/_app/members/$memberId/'
      path: '/members/$memberId'
      fullPath: '/members/$memberId/'
      preLoaderRoute: typeof AppMembersMemberIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/$memberId/edit': {
      id: '/_app/members/$memberId/edit'
      path: '/members/$memberId/edit'
      fullPath: '/members/$memberId/edit'
      preLoaderRoute: typeof AppMembersMemberIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/active/all': {
      id: '/_app/members/active/all'
      path: '/members/active/all'
      fullPath: '/members/active/all'
      preLoaderRoute: typeof AppMembersActiveAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/active/flagged': {
      id: '/_app/members/active/flagged'
      path: '/members/active/flagged'
      fullPath: '/members/active/flagged'
      preLoaderRoute: typeof AppMembersActiveFlaggedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/active/general': {
      id: '/_app/members/active/general'
      path: '/members/active/general'
      fullPath: '/members/active/general'
      preLoaderRoute: typeof AppMembersActiveGeneralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/appeals/': {
      id: '/_app/members/appeals/'
      path: '/members/appeals'
      fullPath: '/members/appeals/'
      preLoaderRoute: typeof AppMembersAppealsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/appeals/$appealId': {
      id: '/_app/members/appeals/$appealId'
      path: '/members/appeals/$appealId'
      fullPath: '/members/appeals/$appealId'
      preLoaderRoute: typeof AppMembersAppealsAppealIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/withdrawn/': {
      id: '/_app/members/withdrawn/'
      path: '/members/withdrawn'
      fullPath: '/members/withdrawn/'
      preLoaderRoute: typeof AppMembersWithdrawnIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/withdrawn/$memberId': {
      id: '/_app/members/withdrawn/$memberId'
      path: '/members/withdrawn/$memberId'
      fullPath: '/members/withdrawn/$memberId'
      preLoaderRoute: typeof AppMembersWithdrawnMemberIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performances/$performanceId/': {
      id: '/_app/performances/$performanceId/'
      path: '/performances/$performanceId'
      fullPath: '/performances/$performanceId/'
      preLoaderRoute: typeof AppPerformancesPerformanceIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performances/$performanceId/edit': {
      id: '/_app/performances/$performanceId/edit'
      path: '/performances/$performanceId/edit'
      fullPath: '/performances/$performanceId/edit'
      preLoaderRoute: typeof AppPerformancesPerformanceIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ticketing/printers/': {
      id: '/_app/ticketing/printers/'
      path: '/ticketing/printers'
      fullPath: '/ticketing/printers/'
      preLoaderRoute: typeof AppTicketingPrintersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ticketing/printers/new': {
      id: '/_app/ticketing/printers/new'
      path: '/ticketing/printers/new'
      fullPath: '/ticketing/printers/new'
      preLoaderRoute: typeof AppTicketingPrintersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community/boards/$boardId/': {
      id: '/_app/community/boards/$boardId/'
      path: '/community/boards/$boardId'
      fullPath: '/community/boards/$boardId/'
      preLoaderRoute: typeof AppCommunityBoardsBoardIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community/boards/$boardId/edit': {
      id: '/_app/community/boards/$boardId/edit'
      path: '/community/boards/$boardId/edit'
      fullPath: '/community/boards/$boardId/edit'
      preLoaderRoute: typeof AppCommunityBoardsBoardIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ticketing/printers/$printerId/': {
      id: '/_app/ticketing/printers/$printerId/'
      path: '/ticketing/printers/$printerId'
      fullPath: '/ticketing/printers/$printerId/'
      preLoaderRoute: typeof AppTicketingPrintersPrinterIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ticketing/printers/$printerId/edit': {
      id: '/_app/ticketing/printers/$printerId/edit'
      path: '/ticketing/printers/$printerId/edit'
      fullPath: '/ticketing/printers/$printerId/edit'
      preLoaderRoute: typeof AppTicketingPrintersPrinterIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppManagersNewRoute: typeof AppManagersNewRoute
  AppMembersAccessRoute: typeof AppMembersAccessRoute
  AppMembersCounselRoute: typeof AppMembersCounselRoute
  AppMembersDormantRoute: typeof AppMembersDormantRoute
  AppMembersNewRoute: typeof AppMembersNewRoute
  AppPerformancesContentsRoute: typeof AppPerformancesContentsRoute
  AppManagersIndexRoute: typeof AppManagersIndexRoute
  AppPerformancesIndexRoute: typeof AppPerformancesIndexRoute
  AppCommunityBoardsNewRoute: typeof AppCommunityBoardsNewRoute
  AppManagersManagerIdEditRoute: typeof AppManagersManagerIdEditRoute
  AppMembersMemberIdEditRoute: typeof AppMembersMemberIdEditRoute
  AppMembersActiveAllRoute: typeof AppMembersActiveAllRoute
  AppMembersActiveFlaggedRoute: typeof AppMembersActiveFlaggedRoute
  AppMembersActiveGeneralRoute: typeof AppMembersActiveGeneralRoute
  AppMembersAppealsAppealIdRoute: typeof AppMembersAppealsAppealIdRoute
  AppMembersWithdrawnMemberIdRoute: typeof AppMembersWithdrawnMemberIdRoute
  AppPerformancesPerformanceIdEditRoute: typeof AppPerformancesPerformanceIdEditRoute
  AppTicketingPrintersNewRoute: typeof AppTicketingPrintersNewRoute
  AppCommunityBoardsIndexRoute: typeof AppCommunityBoardsIndexRoute
  AppManagersManagerIdIndexRoute: typeof AppManagersManagerIdIndexRoute
  AppMembersMemberIdIndexRoute: typeof AppMembersMemberIdIndexRoute
  AppMembersAppealsIndexRoute: typeof AppMembersAppealsIndexRoute
  AppMembersWithdrawnIndexRoute: typeof AppMembersWithdrawnIndexRoute
  AppPerformancesPerformanceIdIndexRoute: typeof AppPerformancesPerformanceIdIndexRoute
  AppTicketingPrintersIndexRoute: typeof AppTicketingPrintersIndexRoute
  AppCommunityBoardsBoardIdEditRoute: typeof AppCommunityBoardsBoardIdEditRoute
  AppTicketingPrintersPrinterIdEditRoute: typeof AppTicketingPrintersPrinterIdEditRoute
  AppCommunityBoardsBoardIdIndexRoute: typeof AppCommunityBoardsBoardIdIndexRoute
  AppTicketingPrintersPrinterIdIndexRoute: typeof AppTicketingPrintersPrinterIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppManagersNewRoute: AppManagersNewRoute,
  AppMembersAccessRoute: AppMembersAccessRoute,
  AppMembersCounselRoute: AppMembersCounselRoute,
  AppMembersDormantRoute: AppMembersDormantRoute,
  AppMembersNewRoute: AppMembersNewRoute,
  AppPerformancesContentsRoute: AppPerformancesContentsRoute,
  AppManagersIndexRoute: AppManagersIndexRoute,
  AppPerformancesIndexRoute: AppPerformancesIndexRoute,
  AppCommunityBoardsNewRoute: AppCommunityBoardsNewRoute,
  AppManagersManagerIdEditRoute: AppManagersManagerIdEditRoute,
  AppMembersMemberIdEditRoute: AppMembersMemberIdEditRoute,
  AppMembersActiveAllRoute: AppMembersActiveAllRoute,
  AppMembersActiveFlaggedRoute: AppMembersActiveFlaggedRoute,
  AppMembersActiveGeneralRoute: AppMembersActiveGeneralRoute,
  AppMembersAppealsAppealIdRoute: AppMembersAppealsAppealIdRoute,
  AppMembersWithdrawnMemberIdRoute: AppMembersWithdrawnMemberIdRoute,
  AppPerformancesPerformanceIdEditRoute: AppPerformancesPerformanceIdEditRoute,
  AppTicketingPrintersNewRoute: AppTicketingPrintersNewRoute,
  AppCommunityBoardsIndexRoute: AppCommunityBoardsIndexRoute,
  AppManagersManagerIdIndexRoute: AppManagersManagerIdIndexRoute,
  AppMembersMemberIdIndexRoute: AppMembersMemberIdIndexRoute,
  AppMembersAppealsIndexRoute: AppMembersAppealsIndexRoute,
  AppMembersWithdrawnIndexRoute: AppMembersWithdrawnIndexRoute,
  AppPerformancesPerformanceIdIndexRoute:
    AppPerformancesPerformanceIdIndexRoute,
  AppTicketingPrintersIndexRoute: AppTicketingPrintersIndexRoute,
  AppCommunityBoardsBoardIdEditRoute: AppCommunityBoardsBoardIdEditRoute,
  AppTicketingPrintersPrinterIdEditRoute:
    AppTicketingPrintersPrinterIdEditRoute,
  AppCommunityBoardsBoardIdIndexRoute: AppCommunityBoardsBoardIdIndexRoute,
  AppTicketingPrintersPrinterIdIndexRoute:
    AppTicketingPrintersPrinterIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
